name: uvc_ot_calculator
description: UV-C OT Disinfection Calculator
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
